SEL = {
    "instagram": {
        "username":   ["//input[@name='username']", "//input[@type='text']"],
        "password":   ["//input[@name='password']", "//input[@type='password']"],
        "login_btn":  ["//button[@type='submit']", "//button[contains(.,'Log in')]"],
        "bad_url":    ["accounts/login", "/login", "/challenge/", "/checkpoint/", "/accounts/suspended"],
        "options":    ["//div[@role='button']//*[local-name()='svg'][@aria-label='More options']",
                       "//svg[@aria-label='More options']",
                       "//button[contains(@aria-label,'More')]"],
        "report":     ["//button[contains(text(),'Report')]", "//div[contains(text(),'Report')]"],
        "submit":     ["//button[contains(text(),'Submit')]", "//button[contains(text(),'Done')]"],
    },
    "twitter": {
        "username":   ["//input[@autocomplete='username']", "//input[@name='text']", "//input[@type='text']"],
        "next":       ["//button[@data-testid='LoginForm_Login_Button']",
                       "//div[@role='button'][contains(.,'Next')]"],
        "email_ver":  ["//input[@data-testid='ocfEnterTextTextInput']"],
        "email_next": ["//div[@data-testid='ocfEnterTextNextButton']"],
        "password":   ["//input[@name='password']", "//input[@type='password']"],
        "login_btn":  ["//button[@data-testid='LoginForm_Login_Button']",
                       "//div[@data-testid='LoginForm_Login_Button']"],
        "bad_url":    ["login", "i/flow"],
        "actions":    ["//button[@data-testid='userActions']",
                       "//div[@data-testid='userActions']",
                       "//button[@aria-label='More']"],
        "report":     ["//span[contains(text(),'Report')]",
                       "//div[@role='menuitem'][contains(.,'Report')]"],
        "submit":     ["//span[contains(text(),'Submit')]", "//button[contains(.,'Done')]"],
    },
    "youtube": {
        "email":      ["//input[@type='email']", "//input[@id='identifierId']"],
        "id_next":    ["//div[@id='identifierNext']", "//button[contains(.,'Next')]"],
        "password":   ["//input[@type='password']"],
        "pw_next":    ["//div[@id='passwordNext']"],
        "bad_url":    ["accounts.google.com"],
        "more":       ["//button[@aria-label='More actions']", "//yt-icon-button[@id='more-options']"],
        "report":     ["//yt-formatted-string[contains(text(),'Report')]",
                       "//tp-yt-paper-item[contains(.,'Report')]"],
        "submit":     ["//button[contains(.,'Submit')]"],
    },
    "facebook": {
        "email":      ["//input[@id='email']", "//input[@type='email']"],
        "password":   ["//input[@id='pass']", "//input[@type='password']"],
        "login_btn":  ["//button[@name='login']", "//button[@type='submit']"],
        "bad_url":    ["login", "checkpoint", "challenge", "identity_confirm"],
        "more":       ["//div[@aria-label='More actions'][@role='button']",
                       "//div[@aria-label='More'][@role='button']"],
        "report":     ["//span[contains(text(),'Find support or report')]",
                       "//span[contains(text(),'Report')]"],
        "submit":     ["//div[@aria-label='Next']", "//button[contains(.,'Submit')]"],
    },
    "tiktok": {
        "username":   ["//input[@name='username']", "//input[@placeholder='Email or username']",
                       "//input[@type='text']"],
        "password":   ["//input[@type='password']"],
        "login_btn":  ["//button[@type='submit']"],
        "bad_url":    ["login"],
        "more":       ["//div[@data-e2e='more']", "//button[contains(@aria-label,'more')]"],
        "report":     ["//p[contains(text(),'Report')]", "//span[contains(text(),'Report')]"],
        "submit":     ["//button[contains(.,'Submit')]"],
    },
    "reddit": {
        "username":   ["//input[@id='loginUsername']", "//input[@name='username']"],
        "password":   ["//input[@id='loginPassword']", "//input[@name='password']"],
        "login_btn":  ["//button[@type='submit']"],
        "bad_url":    ["login"],
        "more":       ["//button[contains(@aria-label,'more options')]",
                       "//button[@id='profile-overflow-button']"],
        "report":     ["//span[contains(text(),'Report')]", "//button[contains(.,'Report User')]"],
        "submit":     ["//button[contains(.,'Submit')]"],
    },
    "discord": {
        "email":           ["//input[@name='email']", "//input[@type='email']"],
        "password":        ["//input[@type='password']"],
        "login_btn":       ["//button[@type='submit']"],
        "bad_url":         ["login"],
        "report_email":    ["//input[@id='anonymous_requester_email']"],
        "report_subject":  ["//input[@id='request_subject']"],
        "report_body":     ["//textarea"],
        "submit":          ["//button[@type='submit']", "//input[@type='submit']"],
    },
    "threads": {
        "username":   ["//input[@autocomplete='username']", "//input[@name='username']"],
        "password":   ["//input[@type='password']"],
        "login_btn":  ["//div[@role='button'][contains(.,'Log in')]"],
        "bad_url":    ["login"],
        "more":       ["//div[@aria-label='More'][@role='button']"],
        "report":     ["//span[contains(text(),'Report')]"],
        "submit":     ["//button[contains(.,'Submit')]"],
    },
    "gmail": {
        "email":      ["//input[@type='email']", "//input[@id='identifierId']"],
        "id_next":    ["//div[@id='identifierNext']"],
        "password":   ["//input[@type='password']"],
        "pw_next":    ["//div[@id='passwordNext']"],
        "bad_url":    ["accounts.google.com"],
        "target_inp": ["//input[@id='emailAddress']"],
        "desc_inp":   ["//textarea"],
        "submit":     ["//input[@type='submit']", "//button[@type='submit']"],
    },
    "snapchat": {
        "target_inp": ["//input[@id='username']", "//input[contains(@placeholder,'username')]"],
        "your_user":  ["//input[@id='yourUsername']"],
        "desc_inp":   ["//textarea"],
        "submit":     ["//button[@type='submit']"],
    },
    "telegram": {
        "login_btn":  ["//button[contains(.,'Log in by phone')]",
                        "//span[contains(.,'Log in by phone number')]"],
        "phone":      ["//input[@type='tel']", "//input[contains(@placeholder,'phone')]"],
        "next":       ["//button[contains(.,'Next')]"],
        "otp":        ["//input[@type='number']", "//input[@inputmode='numeric']"],
        "chat_info":  ["//div[contains(@class,'chat-info')]"],
        "menu_toggle":["//div[@class='btn-menu-toggle']"],
        "report":     ["//div[contains(text(),'Report')]"],
        "report_btn": ["//button[contains(.,'Report')]"],
    },
}

def get_selectors(plat: str, key: str) -> list:
    return SEL.get(plat, {}).get(key, [])

_LOGIN_CHECK_XPATHS = {
    "instagram": ["//a[contains(@href,'/direct/')]", "//span[contains(text(),'Home')]",
                  "//svg[@aria-label='Home']"],
    "twitter":   ["//a[@aria-label='Home']", "//a[@data-testid='AppTabBar_Home_Link']",
                  "//div[@data-testid='SideNav_NewTweet_Button']"],
    "youtube":   ["//button[@aria-label='Account']", "//yt-img-shadow[@id='avatar']"],
    "facebook":  ["//div[@aria-label='Facebook']", "//a[@aria-label='Home']",
                  "//div[@aria-label='Your profile']"],
    "tiktok":    ["//div[@data-e2e='profile-icon']", "//button[@data-e2e='nav-upload-button']"],
    "reddit":    ["//button[contains(@id,'USER_DROPDOWN')]", "//a[contains(@href,'/user/')]"],
    "discord":   ["//div[@aria-label='Direct Messages']"],
    "threads":   ["//a[contains(@href,'/inbox')]", "//div[contains(@aria-label,'Home')]"],
    "gmail":     ["//div[@gh='cm']", "//a[contains(@href,'compose')]"],
    "snapchat":  [],
    "telegram":  [],
}
