"""Tool dialogs — re-exports from split sub-modules + TOOL_DISPATCH."""
from instareport.ui.dialogs_basic import *
from instareport.ui.dialogs_pro import *
from instareport.ui.dialogs_misc import *

TOOL_DISPATCH = {
    "burst_mode": open_burst_mode,
    "emergency_stop": open_emergency_stop,
    "shadow_check": open_shadow_check,
    "account_health": open_account_health,
    "timed_strikes": open_timed_strikes,
    "distributed": open_distributed,
    "thread_manager": open_thread_manager,
    "history_csv": open_history_csv,
    "export_html": open_export_html,
    "auto_update": open_auto_update,
    "telegram_bot": open_telegram_bot,
    "payload_builder": open_payload_builder,
    "force_report": open_force_report,
    "queue_cleaner": open_queue_cleaner,
    "report_templates": open_report_templates,
    "account_groups": open_account_groups,
    "smart_categorize": open_smart_categorize,
    "vip_bypass": open_vip_bypass,
    "turbo_queue": open_turbo_queue,
    "batch_processor": open_batch_processor,
    "api_hook": open_api_hook,
    "appeal": open_appeal,
    "identity_swap": open_identity_swap,
    "cache_purge": open_cache_purge,
    "flag_override": open_flag_override,
    "acc_restore": open_acc_restore,
    "ban_detector": open_ban_detector,
    "warmup": open_warmup,
    "safe_mode": open_safe_mode,
    "proxy_rotate": open_proxy_rotate,
    "session_rebuild": open_session_rebuild,
    "captcha_config": open_captcha_config,
    "twofa_bypass": open_twofa_bypass,
    "profile_scan": open_profile_scan,
    "shadow_check_lookup": open_shadow_check_lookup,
    "engagement": open_engagement,
    "follower_track": open_follower_track,
    "report_history": open_report_history,
    "screenshot_gallery": open_screenshot_gallery,
    "ip_resolve": open_ip_resolve,
    "fingerprint": open_fingerprint,
    "acc_age": open_acc_age,
    "link_trace": open_link_trace,
    "hash_lookup": open_hash_lookup,
    "stealth": open_stealth,
    "dark_pattern": open_dark_pattern,
    "net_spoof": open_net_spoof,
    "behavior": open_behavior,
    "rate_limit": open_rate_limit,
    "header_forge": open_header_forge,
    "cookie_inject": open_cookie_inject,
    "canvas_spoof": open_canvas_spoof,
    "webrtc_block": open_webrtc_block,
    "tls_fp": open_tls_fp,
}
